# Generated by Django 5.1.7 on 2025-04-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_shift_shift_type_alter_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default='morning', max_length=10),
        ),
    ]
